apiVersion: v1
kind: BuildConfig
metadata:
  creationTimestamp: null
  labels:
    app: pipeline
    name: release-sprint-burndown
  name: release-sprint-burndown
spec:
  output: {}
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: "https://github.com/Estafet-LTD/estafet-microservices-scrum-api-sprint-burndown"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: pipelines/release-pipeline.groovy
    type: JenkinsPipeline
status:
  lastVersion: 0